<?php

namespace Aquilinoflores\PhpSecCheck\Tests\Checks;

use Aquilinoflores\PhpSecCheck\Checks\ComposerAuditCheck;
use PHPUnit\Framework\TestCase;

class ComposerAuditCheckTest extends TestCase
{
    private ComposerAuditCheck $check;
    private string $tempDir;

    protected function setUp(): void
    {
        $this->check = new ComposerAuditCheck();
        $this->tempDir = sys_get_temp_dir() . '/php-sec-check-test-' . uniqid();
        mkdir($this->tempDir, 0777, true);
    }

    protected function tearDown(): void
    {
        // Clean up temp files
        foreach (glob($this->tempDir . '/*') as $file) {
            unlink($file);
        }
        rmdir($this->tempDir);
    }

    private function runSilently(string $projectRoot): array
    {
        ob_start();
        $result = $this->check->run($projectRoot);
        ob_end_clean();
        return $result;
    }

    public function test_returns_array(): void
    {
        $result = $this->runSilently($this->tempDir);
        $this->assertIsArray($result);
    }

    public function test_skips_audit_when_no_composer_lock(): void
    {
        // No composer.lock in the temp dir — should return empty and skip.
        $result = $this->runSilently($this->tempDir);
        $this->assertEmpty($result);
    }

    public function test_outputs_info_when_no_composer_lock(): void
    {
        ob_start();
        $this->check->run($this->tempDir);
        $output = ob_get_clean();

        $this->assertStringContainsString('No composer.lock found', $output);
        $this->assertStringContainsString('Skipping', $output);
    }

    public function test_output_contains_dependencies_header(): void
    {
        ob_start();
        $this->check->run($this->tempDir);
        $output = ob_get_clean();

        $this->assertStringContainsString('[COMPOSER DEPENDENCIES]', $output);
    }

    public function test_runs_audit_when_composer_lock_exists(): void
    {
        // Create a minimal valid composer.lock so the audit path is triggered.
        $lockContent = json_encode([
            '_readme' => ['This file is @generated by Composer'],
            'content-hash' => 'abc123',
            'packages' => [],
            'packages-dev' => [],
            'aliases' => [],
            'minimum-stability' => 'stable',
            'stability-flags' => [],
            'prefer-stable' => false,
            'prefer-lowest' => false,
            'platform' => [],
            'platform-dev' => [],
        ]);

        file_put_contents($this->tempDir . '/composer.lock', $lockContent);

        // Should not throw — the exec may fail or return no advisories; either
        // way we expect an array back (possibly empty).
        $result = $this->runSilently($this->tempDir);
        $this->assertIsArray($result);
    }

    public function test_returns_empty_when_no_advisories_found(): void
    {
        // Minimal lock file with no packages — audit should report nothing.
        $lockContent = json_encode([
            'packages' => [],
            'packages-dev' => [],
        ]);

        file_put_contents($this->tempDir . '/composer.lock', $lockContent);

        $result = $this->runSilently($this->tempDir);
        $this->assertEmpty($result);
    }
}
